### ISSUE TITLE
TypeError: string indices must be integers on running 'CheckTransactions'

### ISSUE THREAD

**Issue by MerryLad** [kangasbros/django-bitcoin#21]
Steps to reproduce

Get the latest version from gh.

pip install -r django_bitcoin/requirements.txt

go to your application

run `python manage.py CheckTransactions`

it yields:

```
python manage.py CheckTransactions
starting overall1 0.000110864639282 2013-11-11 01:32:48.944677
starting round 0.00641298294067
TypeError: string indices must be integers
```

Am I doing something wrong? I have tried this with an application that had some running wallets as well as with an empty one, to no avail.

**Comment by MerryLad** [comment]
full stack: (django doesnt provide if not with --traceback)

```
python manage.py CheckTransactions --traceback
starting overall1 7.70092010498e-05 2013-11-11 01:49:56.144735
starting round 0.000697135925293
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 222, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 255, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 385, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/dist-packages/django_bitcoin-0.2-py2.7.egg/django_bitcoin/management/commands/CheckTransactions.py", line 31, in handle_noargs
    if t[u'category'] != u'immature' and (not last_check_time or (int(t['time'])) >= last_check_time) and t[u'amount']>0:
TypeError: string indices must be integers
```

 I will add a patch for it later.
